codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "50...100"

status:
  project:
    default:
      target: auto
      threshold: 1%
  patch:
    default:
      target: auto
      threshold: 1%

# Ignore files/directories that tests won't cover
ignore:
  - "metrics_utility/test/**" # Test files themselves

flags:
  unit-tests:
    carryforward: true
    paths:
      - metrics_utility/

comment:
  layout: "reach,diff,flags,files"
  behavior: default
