#!/bin/sh
set -e
cd "`dirname "$0"`"

export METRICS_UTILITY_SHIP_PATH="./out"
export METRICS_UTILITY_SHIP_TARGET="directory"

# total_workers_vcpu excluded - see ./run-vcpu
export METRICS_UTILITY_OPTIONAL_COLLECTORS="execution_environments,job_host_summary_service,main_host,main_indirectmanagednodeaudit,main_jobevent,main_jobevent_service,unified_jobs"

if ! pg_isready -h localhost; then
  echo "run-ccsp2-gather: DB not ready, run make compose first"
  exit 1
fi

env time -format='\n\nmemory %MK\ncpu %P\ntime %es\n\n' \
uv run ./manage.py gather_automation_controller_billing_data --ship --until=10m --force "$@"

set -x
ls -lR out/data/`date +%Y`/
