#!/bin/sh
set -e
cd "`dirname "$0"`"

export METRICS_UTILITY_REPORT_TYPE="RENEWAL_GUIDANCE"
export METRICS_UTILITY_SHIP_PATH="./out"
export METRICS_UTILITY_SHIP_TARGET="controller_db"

SCHEMA=`realpath "metrics_utility/test/test_data/schemas/awx/latest.sql"`
ROLES=`realpath "metrics_utility/test/test_data/schemas/awx/roles.sql"`
NAME=renewal-`basename "$SCHEMA" .schema`

echo "$NAME"
pg_isready -h localhost ||
podman run --name "$NAME" --replace \
    -e POSTGRES_USER="myuser" \
    -e POSTGRES_PASSWORD="mypassword" \
    -e POSTGRES_DB="awx" \
    -v "$ROLES":/docker-entrypoint-initdb.d/init-roles.sql:ro \
    -v "$SCHEMA":/docker-entrypoint-initdb.d/init-schema.sql:ro \
    -p 5432:5432 \
    -d quay.io/cloudservices/postgres

tries=5
until pg_isready -h localhost; do
  [ "$tries" -lt 1 ] && break

  echo "Waiting for PostgreSQL to be ready...($tries)"
  sleep "$tries"

  tries=`expr "$tries" - 1`
done

uv run ./manage.py build_report --since=12months --ephemeral=1month --force "$@"

podman stop "$NAME"

set -x
ls -lR out/reports/`date +%Y`/
