#!/bin/sh
set -e
cd "`dirname "$0"`"

## cleanup
rm -rf metrics_utility/test/test_data/reports/2026/

## check prerequisites
set -x
ls -lR metrics_utility/test/test_data/data/2026/
set +x

## build_report
export METRICS_UTILITY_REPORT_TYPE="CCSPv2"
export METRICS_UTILITY_SHIP_PATH="./metrics_utility/test/test_data/"
export METRICS_UTILITY_SHIP_TARGET="directory"

run_default_sheets() {
  unset METRICS_UTILITY_OPTIONAL_CCSP_REPORT_SHEETS
  export METRICS_UTILITY_OPTIONAL_CCSP_REPORT_SHEETS

  echo default sheets
  $TIME --format='\n\nmemory %MK\ncpu %P\ntime %es\n\n' \
  uv run ./manage.py build_report --force "$@"
}

run_all_sheets() {
  export METRICS_UTILITY_OPTIONAL_CCSP_REPORT_SHEETS=ccsp_summary,indirectly_managed_nodes,inventory_scope,jobs,managed_nodes,managed_nodes_by_organizations,usage_by_collections,usage_by_modules,usage_by_organizations,usage_by_roles,data_collection_status

  echo all sheets
  $TIME --format='\n\nmemory %MK\ncpu %P\ntime %es\n\n' \
  uv run ./manage.py build_report --force "$@"
}

echo build 10,000
run_default_sheets --month=2026-01
run_all_sheets --month=2026-01

echo build 100,000
run_default_sheets --month=2026-02
run_all_sheets --month=2026-02

echo build 1,000,000
run_default_sheets --month=2026-03
run_all_sheets --month=2026-03

echo build 10,000,000
run_default_sheets --month=2026-04
run_all_sheets --month=2026-04

## checkup
set -x
ls -l metrics_utility/test/test_data/reports/2026/*
