#!/bin/sh
set -e
cd "`dirname "$0"`"

TIME=`command -v gtime >/dev/null && echo 'gtime' || echo '/usr/bin/time'`
measure() {
  "$TIME" --format='\n\nmemory %MK\ncpu %P\ntime %es\n\n' -o /dev/stdout "$@"
}

log() {
  echo `date -Iseconds`: "$@"
}

## cleanup
rm -rf generated/data

run_generator() {
  export MAIN_JOBHOSTSUMMARY_SIZE="$1"
  export MAIN_JOBHOSTSUMMARY_UNIQUE_SIZE="$2"
  export MAIN_HOST_SIZE="$1"
  export MAIN_HOST_UNIQUE_SIZE="$2"
  export MAIN_HOST_FREQUENCY="$5"
  export MAIN_INDIRECT_SIZE="$1"
  export MAIN_INDIRECT_UNIQUE_SIZE="$2"
  export MAIN_JOBEVENT_SIZE="$1"
  export MAIN_JOBEVENT_UNIQUE_SIZE="$2"

  export OUTPUT_DATE_FROM="$3"
  export OUTPUT_DATE_TO="$4"

  export SOURCE_DATA_PATH="../../metrics_utility/test/test_data/data/"
  export OUTPUT_DATA_PATH="./generated/data/"

  measure uv run ./generator.py
}

## generator
log "gen 10,000"
run_generator 10000 2000 2026-01-01 2026-02-01 1

log "gen 100,000"
run_generator 100000 20000 2026-02-01 2026-03-01 7

log "gen 1,000,000"
run_generator 1000000 200000 2026-03-01 2026-04-01 0

## checkup
set -x
ls -lR generated/data/
