#!/bin/sh
set -e
cd "`dirname "$0"`"

## cleanup
rm -rf metrics_utility/test/test_data/data/2026/

## generator
echo gen 10,000
export MAIN_JOBHOSTSUMMARY_SIZE=10000
export MAIN_JOBHOSTSUMMARY_UNIQUE_SIZE=2000
export MAIN_HOST_SIZE=10000
export MAIN_HOST_UNIQUE_SIZE=2000
export MAIN_INDIRECT_SIZE=10000
export MAIN_INDIRECT_UNIQUE_SIZE=2000
export MAIN_JOBEVENT_SIZE=10000
export MAIN_JOBEVENT_UNIQUE_SIZE=2000

export OUTPUT_DATE_FROM=2026-01-01
export OUTPUT_DATE_TO=2026-02-01

TIME=`command -v gtime >/dev/null 2>&1 && echo 'gtime' || echo '/usr/bin/time'`
$TIME --format='\n\nmemory %MK\ncpu %P\ntime %es\n\n' \
uv run ./generator.py

echo gen 100,000
export MAIN_JOBHOSTSUMMARY_SIZE=100000
export MAIN_JOBHOSTSUMMARY_UNIQUE_SIZE=20000
export MAIN_HOST_SIZE=100000
export MAIN_HOST_UNIQUE_SIZE=20000
export MAIN_INDIRECT_SIZE=100000
export MAIN_INDIRECT_UNIQUE_SIZE=20000
export MAIN_JOBEVENT_SIZE=100000
export MAIN_JOBEVENT_UNIQUE_SIZE=20000

export OUTPUT_DATE_FROM=2026-02-01
export OUTPUT_DATE_TO=2026-03-01
$TIME --format='\n\nmemory %MK\ncpu %P\ntime %es\n\n' \
uv run ./generator.py

# ~5 minutes
echo gen 1,000,000
export MAIN_JOBHOSTSUMMARY_SIZE=1000000
export MAIN_JOBHOSTSUMMARY_UNIQUE_SIZE=200000
export MAIN_HOST_SIZE=1000000
export MAIN_HOST_UNIQUE_SIZE=200000
export MAIN_INDIRECT_SIZE=1000000
export MAIN_INDIRECT_UNIQUE_SIZE=200000
export MAIN_JOBEVENT_SIZE=1000000
export MAIN_JOBEVENT_UNIQUE_SIZE=200000

export OUTPUT_DATE_FROM=2026-03-01
export OUTPUT_DATE_TO=2026-04-01

$TIME --format='\n\nmemory %MK\ncpu %P\ntime %es\n\n' \
uv run ./generator.py

## ~50 minutes
echo gen 10,000,000
export MAIN_JOBHOSTSUMMARY_SIZE=10000000
export MAIN_JOBHOSTSUMMARY_UNIQUE_SIZE=2000000
export MAIN_HOST_SIZE=10000000
export MAIN_HOST_UNIQUE_SIZE=2000000
export MAIN_INDIRECT_SIZE=10000000
export MAIN_INDIRECT_UNIQUE_SIZE=2000000
export MAIN_JOBEVENT_SIZE=10000000
export MAIN_JOBEVENT_UNIQUE_SIZE=2000000

export OUTPUT_DATE_FROM=2026-04-01
export OUTPUT_DATE_TO=2026-05-01

$TIME --format='\n\nmemory %MK\ncpu %P\ntime %es\n\n' \
uv run ./generator.py

## checkup
set -x
ls -lR metrics_utility/test/test_data/data/2026/
