location /static {
    alias /var/lib/awx/public/static/;
}

location /locales {
    alias /var/lib/awx/public/static/awx/locales;
}

location /favicon.ico {
    alias /awx_devel/awx/public/static/favicon.ico;
}

location ~ ^(/websocket/|/api/websocket/) {
    proxy_pass http://daphne;
    proxy_http_version 1.1;
    proxy_buffering off;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header Host $http_host;
    proxy_redirect off;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
}

location / {
    rewrite ^(.*)$http_host(.*[^/])$ $1$http_host$2/ permanent;
    uwsgi_read_timeout 120s;
    uwsgi_pass uwsgi;
    include /etc/nginx/uwsgi_params;
    error_page 502 = @fallback;
}

location @fallback {
    rewrite ^(.*)$http_host(.*[^/])$ $1$http_host$2/ permanent;
    proxy_pass http://runserver;
    proxy_set_header Host $http_host;
}
