---
- node:
    id: awx-1
    firewallrules:
      - action: "reject"
        tonode: awx-1
        toservice: "control"

- log-level: info

- tcp-listener:
    port: 2222

- control-service:
    service: control
    filename: /var/run/awx-receptor/receptor.sock

- work-command:
    worktype: local
    command: ansible-runner
    params: worker
    allowruntimeparams: true
    verifysignature: False
