[supervisord]
umask = 022
minfds = 4096
nodaemon = true
pidfile = /var/run/supervisor/supervisord.pid
# nodaemon already logs to stdout
logfile = /dev/null
logfile_maxbytes = 0

[unix_http_server]
file = /var/run/supervisor/supervisor.sock

[supervisorctl]
serverurl = unix:///var/run/supervisor/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

# awx.main.utils.reload restarts programs in the tower-processes group via supervisorctl
[group:tower-processes]
programs = awx-dispatcher,awx-receiver,awx-uwsgi,awx-daphne,awx-nginx,awx-wsrelay,awx-ws-heartbeat,awx-cache-clear
priority = 5

[program:awx-dispatcher]
command = awx-manage dispatcherd
autorestart = true
stopasgroup = true
killasgroup = true
stdout_logfile = /dev/stdout
stdout_logfile_maxbytes = 0
redirect_stderr = true

[program:awx-receiver]
command = awx-manage run_callback_receiver
autorestart = true
stopasgroup = true
killasgroup = true
stdout_logfile = /dev/stdout
stdout_logfile_maxbytes = 0
redirect_stderr = true

[program:awx-wsrelay]
command = awx-manage run_wsrelay
autorestart = true
stopasgroup = true
killasgroup = true
stdout_logfile = /dev/stdout
stdout_logfile_maxbytes = 0
redirect_stderr = true

[program:awx-ws-heartbeat]
command = awx-manage run_ws_heartbeat
autorestart = true
stopasgroup = true
killasgroup = true
stdout_logfile = /dev/stdout
stdout_logfile_maxbytes = 0
redirect_stderr = true

[program:awx-cache-clear]
command = awx-manage run_cache_clear
autorestart = true
stopasgroup = true
killasgroup = true
stdout_logfile = /dev/stdout
stdout_logfile_maxbytes = 0
redirect_stderr = true

[program:awx-uwsgi]
command = uwsgi /etc/tower/uwsgi.ini
autorestart = true
stopwaitsecs = 1
stopsignal = KILL
stopasgroup = true
killasgroup = true
stdout_logfile = /dev/stdout
stdout_logfile_maxbytes = 0
redirect_stderr = true

[program:awx-daphne]
command = daphne -b 127.0.0.1 -p 8051 awx.asgi:channel_layer
autorestart = true
stopasgroup = true
killasgroup = true
stdout_logfile = /dev/stdout
stdout_logfile_maxbytes = 0
redirect_stderr = true

[program:awx-nginx]
command = nginx -g "daemon off;"
autorestart = true
stopasgroup = true
killasgroup = true
stdout_logfile = /dev/stdout
stdout_logfile_maxbytes = 0
redirect_stderr = true

[program:awx-receptor]
command = receptor --config /etc/receptor/receptor.conf
autorestart = true
stopasgroup = true
killasgroup = true
stdout_logfile = /dev/stdout
stdout_logfile_maxbytes = 0
redirect_stderr = true
