# events data for tests for anonymized events rollups

from datetime import datetime, timedelta

import pandas as pd

from metrics_utility.anonymized_rollups.events_anonymized_rollups import Event_Anonymized_Rollups


base_time = datetime(2024, 1, 1, 9, 0, 0)

events_data = [
    # job_1: site.yml, mostly successful with some retries
    {
        'event': 'runner_on_failed',
        'resolved_action': 'collection_1.network.ping',
        'host_id': 'host-a',
        'playbook': 'site.yml',
        'job_id': 'job_1',
        'job_created': base_time,
        'job_started': base_time + timedelta(minutes=5),
        'job_finished': base_time + timedelta(minutes=25),
        'job_failed': False,
        'task_uuid': 'job1-task1-host-a',
    },
    {
        'event': 'runner_on_ok',
        'resolved_action': 'collection_1.network.ping',
        'host_id': 'host-a',
        'playbook': 'site.yml',
        'job_id': 'job_1',
        'job_created': base_time,
        'job_started': base_time + timedelta(minutes=5),
        'job_finished': base_time + timedelta(minutes=25),
        'job_failed': False,
        'task_uuid': 'job1-task1-host-a',
    },
    {
        'event': 'runner_on_ok',
        'resolved_action': 'collection_1.network.ping',
        'host_id': 'host-b',
        'playbook': 'site.yml',
        'job_id': 'job_1',
        'job_created': base_time,
        'job_started': base_time + timedelta(minutes=5),
        'job_finished': base_time + timedelta(minutes=25),
        'job_failed': False,
        'task_uuid': 'job1-task1-host-b',
    },
    {
        'event': 'runner_on_failed',
        'resolved_action': 'collection_1.network.traceroute',
        'host_id': 'host-a',
        'playbook': 'site.yml',
        'job_id': 'job_1',
        'job_created': base_time,
        'job_started': base_time + timedelta(minutes=5),
        'job_finished': base_time + timedelta(minutes=25),
        'job_failed': False,
        'task_uuid': 'job1-task2-host-a',
    },
    {
        'event': 'runner_on_ok',
        'resolved_action': 'collection_1.network.traceroute',
        'host_id': 'host-a',
        'playbook': 'site.yml',
        'job_id': 'job_1',
        'job_created': base_time,
        'job_started': base_time + timedelta(minutes=5),
        'job_finished': base_time + timedelta(minutes=25),
        'job_failed': False,
        'task_uuid': 'job1-task2-host-a',
    },
    {
        'event': 'runner_on_ok',
        'resolved_action': 'collection_1.network.traceroute',
        'host_id': 'host-b',
        'playbook': 'site.yml',
        'job_id': 'job_1',
        'job_created': base_time,
        'job_started': base_time + timedelta(minutes=5),
        'job_finished': base_time + timedelta(minutes=25),
        'job_failed': False,
        'task_uuid': 'job1-task2-host-b',
    },
    # job_2: db.yml, failing job
    {
        'event': 'runner_on_failed',
        'resolved_action': 'collection_2.system.user',
        'host_id': 'host-a',
        'playbook': 'db.yml',
        'job_id': 'job_2',
        'job_created': base_time + timedelta(hours=1),
        'job_started': base_time + timedelta(hours=1, minutes=10),
        'job_finished': base_time + timedelta(hours=1, minutes=35),
        'job_failed': True,
        'task_uuid': 'job2-task1-host-a',
    },
    {
        'event': 'runner_on_failed',
        'resolved_action': 'collection_2.system.user',
        'host_id': 'host-a',
        'playbook': 'db.yml',
        'job_id': 'job_2',
        'job_created': base_time + timedelta(hours=1),
        'job_started': base_time + timedelta(hours=1, minutes=10),
        'job_finished': base_time + timedelta(hours=1, minutes=35),
        'job_failed': True,
        'task_uuid': 'job2-task1-host-a',
    },
    {
        'event': 'runner_on_failed',
        'resolved_action': 'collection_2.system.user',
        'host_id': 'host-b',
        'playbook': 'db.yml',
        'job_id': 'job_2',
        'job_created': base_time + timedelta(hours=1),
        'job_started': base_time + timedelta(hours=1, minutes=10),
        'job_finished': base_time + timedelta(hours=1, minutes=35),
        'job_failed': True,
        'task_uuid': 'job2-task1-host-b',
    },
    {
        'event': 'runner_on_unreachable',
        'resolved_action': 'collection_2.system.user',
        'host_id': 'host-b',
        'playbook': 'db.yml',
        'job_id': 'job_2',
        'job_created': base_time + timedelta(hours=1),
        'job_started': base_time + timedelta(hours=1, minutes=10),
        'job_finished': base_time + timedelta(hours=1, minutes=35),
        'job_failed': True,
        'task_uuid': 'job2-task1-host-b',
    },
    # job_3: web.yml, mixed results, some events use task_action (no resolved_action)
    {
        'event': 'runner_on_skipped',
        'task_action': 'collection_3.files.copy',
        'host_id': 'host-a',
        'playbook': 'web.yml',
        'job_id': 'job_3',
        'job_created': base_time + timedelta(hours=2),
        'job_started': base_time + timedelta(hours=2, minutes=2),
        'job_finished': base_time + timedelta(hours=2, minutes=20),
        'job_failed': False,
        'task_uuid': 'job3-task1-host-a',
    },
    {
        'event': 'runner_on_ok',
        'task_action': 'collection_3.files.copy',
        'host_id': 'host-a',
        'playbook': 'web.yml',
        'job_id': 'job_3',
        'job_created': base_time + timedelta(hours=2),
        'job_started': base_time + timedelta(hours=2, minutes=2),
        'job_finished': base_time + timedelta(hours=2, minutes=20),
        'job_failed': False,
        'task_uuid': 'job3-task1-host-a',
    },
    {
        'event': 'runner_on_ok',
        'task_action': 'collection_3.files.copy',
        'host_id': 'host-b',
        'playbook': 'web.yml',
        'job_id': 'job_3',
        'job_created': base_time + timedelta(hours=2),
        'job_started': base_time + timedelta(hours=2, minutes=2),
        'job_finished': base_time + timedelta(hours=2, minutes=20),
        'job_failed': False,
        'task_uuid': 'job3-task1-host-b',
    },
    {
        'event': 'runner_on_failed',
        'task_action': 'collection_3.service.restart',
        'host_id': 'host-a',
        'playbook': 'web.yml',
        'job_id': 'job_3',
        'job_created': base_time + timedelta(hours=2),
        'job_started': base_time + timedelta(hours=2, minutes=2),
        'job_finished': base_time + timedelta(hours=2, minutes=20),
        'job_failed': False,
        'task_uuid': 'job3-task2-host-a',
    },
    {
        'event': 'runner_on_ok',
        'task_action': 'collection_3.service.restart',
        'host_id': 'host-a',
        'playbook': 'web.yml',
        'job_id': 'job_3',
        'job_created': base_time + timedelta(hours=2),
        'job_started': base_time + timedelta(hours=2, minutes=2),
        'job_finished': base_time + timedelta(hours=2, minutes=20),
        'job_failed': False,
        'task_uuid': 'job3-task2-host-a',
    },
    {
        'event': 'runner_on_ok',
        'task_action': 'collection_3.service.restart',
        'host_id': 'host-b',
        'playbook': 'web.yml',
        'job_id': 'job_3',
        'job_created': base_time + timedelta(hours=2),
        'job_started': base_time + timedelta(hours=2, minutes=2),
        'job_finished': base_time + timedelta(hours=2, minutes=20),
        'job_failed': False,
        'task_uuid': 'job3-task2-host-b',
    },
    # job_4: infra.yml, unreachable then recovered
    {
        'event': 'runner_on_unreachable',
        'resolved_action': 'collection_4.cloud.create',
        'host_id': 'host-a',
        'playbook': 'infra.yml',
        'job_id': 'job_4',
        'job_created': base_time + timedelta(hours=3),
        'job_started': base_time + timedelta(hours=3, minutes=1),
        'job_finished': base_time + timedelta(hours=3, minutes=30),
        'job_failed': False,
        'task_uuid': 'job4-task1-host-a',
    },
    {
        'event': 'runner_on_ok',
        'resolved_action': 'collection_4.cloud.create',
        'host_id': 'host-a',
        'playbook': 'infra.yml',
        'job_id': 'job_4',
        'job_created': base_time + timedelta(hours=3),
        'job_started': base_time + timedelta(hours=3, minutes=1),
        'job_finished': base_time + timedelta(hours=3, minutes=30),
        'job_failed': False,
        'task_uuid': 'job4-task1-host-a',
    },
    {
        'event': 'runner_on_ok',
        'resolved_action': 'collection_4.cloud.create',
        'host_id': 'host-b',
        'playbook': 'infra.yml',
        'job_id': 'job_4',
        'job_created': base_time + timedelta(hours=3),
        'job_started': base_time + timedelta(hours=3, minutes=1),
        'job_finished': base_time + timedelta(hours=3, minutes=30),
        'job_failed': False,
        'task_uuid': 'job4-task1-host-b',
    },
    {
        'event': 'runner_on_ok',
        'resolved_action': 'collection_4.storage.volume',
        'host_id': 'host-a',
        'playbook': 'infra.yml',
        'job_id': 'job_4',
        'job_created': base_time + timedelta(hours=3),
        'job_started': base_time + timedelta(hours=3, minutes=1),
        'job_finished': base_time + timedelta(hours=3, minutes=30),
        'job_failed': False,
        'task_uuid': 'job4-task2-host-a',
    },
    {
        'event': 'runner_on_ok',
        'resolved_action': 'collection_4.storage.volume',
        'host_id': 'host-b',
        'playbook': 'infra.yml',
        'job_id': 'job_4',
        'job_created': base_time + timedelta(hours=3),
        'job_started': base_time + timedelta(hours=3, minutes=1),
        'job_finished': base_time + timedelta(hours=3, minutes=30),
        'job_failed': False,
        'task_uuid': 'job4-task2-host-b',
    },
    # job_5: security.yml, mixed and failing overall
    {
        'event': 'runner_on_failed',
        'resolved_action': 'collection_5.security.firewall',
        'host_id': 'host-a',
        'playbook': 'security.yml',
        'job_id': 'job_5',
        'job_created': base_time + timedelta(hours=4),
        'job_started': base_time + timedelta(hours=4, minutes=6),
        'job_finished': base_time + timedelta(hours=4, minutes=40),
        'job_failed': True,
        'task_uuid': 'job5-task1-host-a',
    },
    {
        'event': 'runner_on_failed',
        'resolved_action': 'collection_5.security.firewall',
        'host_id': 'host-a',
        'playbook': 'security.yml',
        'job_id': 'job_5',
        'job_created': base_time + timedelta(hours=4),
        'job_started': base_time + timedelta(hours=4, minutes=6),
        'job_finished': base_time + timedelta(hours=4, minutes=40),
        'job_failed': True,
        'task_uuid': 'job5-task1-host-a',
    },
    {
        'event': 'runner_on_ok',
        'resolved_action': 'collection_5.security.firewall',
        'host_id': 'host-b',
        'playbook': 'security.yml',
        'job_id': 'job_5',
        'job_created': base_time + timedelta(hours=4),
        'job_started': base_time + timedelta(hours=4, minutes=6),
        'job_finished': base_time + timedelta(hours=4, minutes=40),
        'job_failed': True,
        'task_uuid': 'job5-task1-host-b',
    },
    {
        'event': 'runner_on_failed',
        'resolved_action': 'collection_5.audit.scan',
        'host_id': 'host-a',
        'playbook': 'security.yml',
        'job_id': 'job_5',
        'job_created': base_time + timedelta(hours=4),
        'job_started': base_time + timedelta(hours=4, minutes=6),
        'job_finished': base_time + timedelta(hours=4, minutes=40),
        'job_failed': True,
        'task_uuid': 'job5-task2-host-a',
    },
    {
        'event': 'runner_on_ok',
        'resolved_action': 'collection_5.audit.scan',
        'host_id': 'host-a',
        'playbook': 'security.yml',
        'job_id': 'job_5',
        'job_created': base_time + timedelta(hours=4),
        'job_started': base_time + timedelta(hours=4, minutes=6),
        'job_finished': base_time + timedelta(hours=4, minutes=40),
        'job_failed': True,
        'task_uuid': 'job5-task2-host-a',
    },
    {
        'event': 'runner_on_failed',
        'resolved_action': 'collection_5.audit.scan',
        'host_id': 'host-b',
        'playbook': 'security.yml',
        'job_id': 'job_5',
        'job_created': base_time + timedelta(hours=4),
        'job_started': base_time + timedelta(hours=4, minutes=6),
        'job_finished': base_time + timedelta(hours=4, minutes=40),
        'job_failed': True,
        'task_uuid': 'job5-task2-host-b',
    },
    # job_6: ops.yml, multiple modules
    {
        'event': 'runner_on_ok',
        'resolved_action': 'collection_1.network.ping',
        'host_id': 'host-a',
        'playbook': 'ops.yml',
        'job_id': 'job_6',
        'job_created': base_time + timedelta(hours=5),
        'job_started': base_time + timedelta(hours=5, minutes=3),
        'job_finished': base_time + timedelta(hours=5, minutes=28),
        'job_failed': False,
        'task_uuid': 'job6-task1-host-a',
    },
    {
        'event': 'runner_on_failed',
        'resolved_action': 'collection_2.system.package',
        'host_id': 'host-a',
        'playbook': 'ops.yml',
        'job_id': 'job_6',
        'job_created': base_time + timedelta(hours=5),
        'job_started': base_time + timedelta(hours=5, minutes=3),
        'job_finished': base_time + timedelta(hours=5, minutes=28),
        'job_failed': False,
        'task_uuid': 'job6-task2-host-a',
    },
    {
        'event': 'runner_on_ok',
        'resolved_action': 'collection_2.system.package',
        'host_id': 'host-a',
        'playbook': 'ops.yml',
        'job_id': 'job_6',
        'job_created': base_time + timedelta(hours=5),
        'job_started': base_time + timedelta(hours=5, minutes=3),
        'job_finished': base_time + timedelta(hours=5, minutes=28),
        'job_failed': False,
        'task_uuid': 'job6-task2-host-a',
    },
    {
        'event': 'runner_on_ok',
        'resolved_action': 'collection_3.files.copy',
        'host_id': 'host-b',
        'playbook': 'ops.yml',
        'job_id': 'job_6',
        'job_created': base_time + timedelta(hours=5),
        'job_started': base_time + timedelta(hours=5, minutes=3),
        'job_finished': base_time + timedelta(hours=5, minutes=28),
        'job_failed': False,
        'task_uuid': 'job6-task1-host-b',
    },
    {
        'event': 'runner_on_unreachable',
        'resolved_action': 'collection_3.files.copy',
        'host_id': 'host-b',
        'playbook': 'ops.yml',
        'job_id': 'job_6',
        'job_created': base_time + timedelta(hours=5),
        'job_started': base_time + timedelta(hours=5, minutes=3),
        'job_finished': base_time + timedelta(hours=5, minutes=28),
        'job_failed': False,
        'task_uuid': 'job6-task1-host-b',
    },
    {
        'event': 'runner_on_ok',
        'resolved_action': 'collection_4.cloud.scale',
        'host_id': 'host-a',
        'playbook': 'ops.yml',
        'job_id': 'job_6',
        'job_created': base_time + timedelta(hours=5),
        'job_started': base_time + timedelta(hours=5, minutes=3),
        'job_finished': base_time + timedelta(hours=5, minutes=28),
        'job_failed': False,
        'task_uuid': 'job6-task3-host-a',
    },
    {
        'event': 'runner_on_failed',
        'resolved_action': 'collection_5.security.audit',
        'host_id': 'host-b',
        'playbook': 'ops.yml',
        'job_id': 'job_6',
        'job_created': base_time + timedelta(hours=5),
        'job_started': base_time + timedelta(hours=5, minutes=3),
        'job_finished': base_time + timedelta(hours=5, minutes=28),
        'job_failed': False,
        'task_uuid': 'job6-task4-host-b',
    },
    {
        'event': 'runner_on_ok',
        'resolved_action': 'collection_5.security.audit',
        'host_id': 'host-b',
        'playbook': 'ops.yml',
        'job_id': 'job_6',
        'job_created': base_time + timedelta(hours=5),
        'job_started': base_time + timedelta(hours=5, minutes=3),
        'job_finished': base_time + timedelta(hours=5, minutes=28),
        'job_failed': False,
        'task_uuid': 'job6-task4-host-b',
    },
]

# test the Event_Anonymized_Rollups


def test_events_anonymized_rollups():
    df = pd.DataFrame(events_data)
    result = Event_Anonymized_Rollups.base(df)

    events_collections = result['event_collections_aggregations']
    events_modules = result['events_modules_aggregations']

    # --- event_collections_aggregations ---
    assert str(events_collections['total_jobs_by_collection_source'].dtype) == 'int64'
    assert str(events_collections['avg_job_duration_by_collection_source'].dtype) == 'timedelta64[ns]'
    assert str(events_collections['avg_job_waiting_time_by_collection_source'].dtype) == 'timedelta64[ns]'
    assert str(events_collections['avg_hosts_per_job_by_collection_source'].dtype) == 'float64'
    assert str(events_collections['failed_jobs_by_collection_source'].dtype) == 'int64'
    assert str(events_collections['success_jobs_by_collection_source'].dtype) == 'int64'
    assert str(events_collections['success_rate_by_collection_source'].dtype) == 'float64'

    # --- events_modules_aggregations ---
    assert events_modules['total_modules_used_to_automate'] == 12
    assert events_modules['avg_number_of_modules_used_in_a_playbook'] == 2.3333333333333335
    assert events_modules['list_of_modules_used_to_automate'] == [
        'collection_1.network.ping',
        'collection_1.network.traceroute',
        'collection_2.system.user',
        'collection_3.files.copy',
        'collection_3.service.restart',
        'collection_4.cloud.create',
        'collection_4.storage.volume',
        'collection_5.security.firewall',
        'collection_5.audit.scan',
        'collection_2.system.package',
        'collection_4.cloud.scale',
        'collection_5.security.audit',
    ]

    expected_module_stats = [
        {
            'module_name': 'collection_1.network.ping',
            'jobs_total': 2,
            'hosts_total': 2,
            'runs_total': 3,
            'runs_success': 3,
            'runs_failed': 0,
            'runs_other': 0,
            'total_failed_attempts': 1,
        },
        {
            'module_name': 'collection_1.network.traceroute',
            'jobs_total': 1,
            'hosts_total': 2,
            'runs_total': 2,
            'runs_success': 2,
            'runs_failed': 0,
            'runs_other': 0,
            'total_failed_attempts': 1,
        },
        {
            'module_name': 'collection_2.system.package',
            'jobs_total': 1,
            'hosts_total': 1,
            'runs_total': 1,
            'runs_success': 1,
            'runs_failed': 0,
            'runs_other': 0,
            'total_failed_attempts': 1,
        },
        {
            'module_name': 'collection_2.system.user',
            'jobs_total': 1,
            'hosts_total': 2,
            'runs_total': 2,
            'runs_success': 0,
            'runs_failed': 2,
            'runs_other': 0,
            'total_failed_attempts': 4,
        },
        {
            'module_name': 'collection_3.files.copy',
            'jobs_total': 2,
            'hosts_total': 2,
            'runs_total': 3,
            'runs_success': 3,
            'runs_failed': 0,
            'runs_other': 0,
            'total_failed_attempts': 1,
        },
        {
            'module_name': 'collection_3.service.restart',
            'jobs_total': 1,
            'hosts_total': 2,
            'runs_total': 2,
            'runs_success': 2,
            'runs_failed': 0,
            'runs_other': 0,
            'total_failed_attempts': 1,
        },
        {
            'module_name': 'collection_4.cloud.create',
            'jobs_total': 1,
            'hosts_total': 2,
            'runs_total': 2,
            'runs_success': 2,
            'runs_failed': 0,
            'runs_other': 0,
            'total_failed_attempts': 1,
        },
        {
            'module_name': 'collection_4.cloud.scale',
            'jobs_total': 1,
            'hosts_total': 1,
            'runs_total': 1,
            'runs_success': 1,
            'runs_failed': 0,
            'runs_other': 0,
            'total_failed_attempts': 0,
        },
        {
            'module_name': 'collection_4.storage.volume',
            'jobs_total': 1,
            'hosts_total': 2,
            'runs_total': 2,
            'runs_success': 2,
            'runs_failed': 0,
            'runs_other': 0,
            'total_failed_attempts': 0,
        },
        {
            'module_name': 'collection_5.audit.scan',
            'jobs_total': 1,
            'hosts_total': 2,
            'runs_total': 2,
            'runs_success': 1,
            'runs_failed': 1,
            'runs_other': 0,
            'total_failed_attempts': 2,
        },
        {
            'module_name': 'collection_5.security.audit',
            'jobs_total': 1,
            'hosts_total': 1,
            'runs_total': 1,
            'runs_success': 1,
            'runs_failed': 0,
            'runs_other': 0,
            'total_failed_attempts': 1,
        },
        {
            'module_name': 'collection_5.security.firewall',
            'jobs_total': 1,
            'hosts_total': 2,
            'runs_total': 2,
            'runs_success': 1,
            'runs_failed': 1,
            'runs_other': 0,
            'total_failed_attempts': 2,
        },
    ]

    assert events_modules['module_stats'] == expected_module_stats
