FROM alpine:3
RUN apk add --no-cache curl && \
    curl -fL https://garagehq.deuxfleurs.fr/_releases/v2.3.0/x86_64-unknown-linux-musl/garage -o /garage && \
    chmod +x /garage && \
    apk del curl
EXPOSE 3900 3901
