name: "PR checks"

on:
  pull_request:

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    steps:
      - name: "Check PR target"
        env:
          BASE_REPO: ${{ github.event.pull_request.base.repo.full_name }}
          BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
        run: |
          if [[ "$BASE_REPO" == "ansible/metrics-utility" && "$BASE_BRANCH" == "devel" ]]; then
            echo "✓ PR targets devel on upstream"
          elif [[ "$BASE_BRANCH" == stable-* ]]; then
            echo "✓ PR targets $BASE_BRANCH"
          else
            echo "::error::PRs should target devel on ansible/metrics-utility or a stable-* branch"
            exit 1
          fi

      - name: "Checkout metrics-utility (${{ github.ref }})"
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: "Install uv"
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7

      - name: "Set up Python"
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version-file: "pyproject.toml"

      - name: "Check for changes in uv.lock"
        run: |
          uv sync
          if ! git diff --quiet uv.lock; then
            echo "uv.lock has changed. Run 'uv sync' locally and commit the updated lock file."
            git diff uv.lock
            exit 1  # Fail the job
          fi

      - name: "Run ruff check"
        run: |
          uvx ruff check --output-format=github .

      - name: "Check ruff format"
        run: |
          uvx ruff format --check

      - name: "One logger to rule them all"
        run: |
          if rgrep "logging.getLogger(" metrics_utility | cut -d: -f1 | grep -v logger.py | grep . ; then
            echo "^ Please use logger imported from metrics_utility.logger instead of creating a new one" 1>&2
            false
          else
            true
          fi
