name: SAST Snyk Code
on:
  schedule:
    - cron: '23 14 * * 6'
  workflow_dispatch:
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: snyk/actions/setup@8e119fbb6c251787721d34ba683ed48eba792766 # master

      - name: Generate code vulnerability report
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk code test --project-name="${{ github.repository }}" --report ${{ github.workspace }}
        continue-on-error: true