name: "SonarCloud scan"

on:
  pull_request_target:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout metrics-utility (${{ github.ref }})"
        uses: actions/checkout@v4

      - name: "SonarCloud scan"
        uses: sonarsource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=ansible_metrics-utility
            -Dsonar.organization=ansible
            -Dsonar.host.url=https://sonarcloud.io
