name: SonarCloud Scan

on:
  pull_request:
    branches:
      - devel

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest


  steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SonarCloud Scan
          uses: sonarsource/sonarcloud-github-action@v2
          with:
            args: >
              -Dsonar.projectKey=ansible_metrics-utility
              -Dsonar.organization=ansible
              -Dsonar.host.url=https://sonarcloud.io
            token: ${{ secrets.SONAR_TOKEN }}